apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: docs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: docs
      labels:
        app: docs
    spec:
      containers:
      - image: ghcr.io/anton-devops/pm-app/docs:v1.1.1
        name: docs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8000