apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: ghcr.io/anton-devops/pm-app/db:v1.1.1
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"  
        - name: POSTGRES_USER
          value: "postgres" 
        - name: POSTGRES_DB
          value: "postgres"
