apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - image: ghcr.io/anton-devops/pm-app/app:v1.1.1
        name: app
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"  
        - name: POSTGRES_USER
          value: "postgres" 
        - name: POSTGRES_HOST
          value: "10.105.187.46"
        - name: POSTGRES_DB
          value: "postgres"
